// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/poolrebalancer/v1/poolrebalancer.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the poolrebalancer module.
type Params struct {
	// pool_delegator_address is the account whose stake is rebalanced.
	PoolDelegatorAddress string `protobuf:"bytes,1,opt,name=pool_delegator_address,json=poolDelegatorAddress,proto3" json:"pool_delegator_address,omitempty"`
	// max_target_validators caps the bonded validator set size (top N by power).
	MaxTargetValidators uint32 `protobuf:"varint,2,opt,name=max_target_validators,json=maxTargetValidators,proto3" json:"max_target_validators,omitempty"`
	// rebalance_threshold_bp is the drift threshold in basis points.
	RebalanceThresholdBp uint32 `protobuf:"varint,3,opt,name=rebalance_threshold_bp,json=rebalanceThresholdBp,proto3" json:"rebalance_threshold_bp,omitempty"`
	// max_ops_per_block caps redelegation operations per block.
	MaxOpsPerBlock uint32 `protobuf:"varint,4,opt,name=max_ops_per_block,json=maxOpsPerBlock,proto3" json:"max_ops_per_block,omitempty"`
	// max_move_per_op caps the amount moved per operation (0 = no cap).
	MaxMovePerOp cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=max_move_per_op,json=maxMovePerOp,proto3,customtype=cosmossdk.io/math.Int" json:"max_move_per_op"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcdfba81f65d424, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// PendingRedelegation is an in-flight redelegation tracked for transitive redelegation safety.
type PendingRedelegation struct {
	DelegatorAddress    string     `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	SrcValidatorAddress string     `protobuf:"bytes,2,opt,name=src_validator_address,json=srcValidatorAddress,proto3" json:"src_validator_address,omitempty"`
	DstValidatorAddress string     `protobuf:"bytes,3,opt,name=dst_validator_address,json=dstValidatorAddress,proto3" json:"dst_validator_address,omitempty"`
	Amount              types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
	CompletionTime      time.Time  `protobuf:"bytes,5,opt,name=completion_time,json=completionTime,proto3,stdtime" json:"completion_time"`
}

func (m *PendingRedelegation) Reset()         { *m = PendingRedelegation{} }
func (m *PendingRedelegation) String() string { return proto.CompactTextString(m) }
func (*PendingRedelegation) ProtoMessage()    {}
func (*PendingRedelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcdfba81f65d424, []int{1}
}
func (m *PendingRedelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingRedelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingRedelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingRedelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingRedelegation.Merge(m, src)
}
func (m *PendingRedelegation) XXX_Size() int {
	return m.Size()
}
func (m *PendingRedelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingRedelegation.DiscardUnknown(m)
}

var xxx_messageInfo_PendingRedelegation proto.InternalMessageInfo

// QueuedRedelegation groups redelegations that share the same completion time.
type QueuedRedelegation struct {
	Entries []PendingRedelegation `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
}

func (m *QueuedRedelegation) Reset()         { *m = QueuedRedelegation{} }
func (m *QueuedRedelegation) String() string { return proto.CompactTextString(m) }
func (*QueuedRedelegation) ProtoMessage()    {}
func (*QueuedRedelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcdfba81f65d424, []int{2}
}
func (m *QueuedRedelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedRedelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedRedelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedRedelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedRedelegation.Merge(m, src)
}
func (m *QueuedRedelegation) XXX_Size() int {
	return m.Size()
}
func (m *QueuedRedelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedRedelegation.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedRedelegation proto.InternalMessageInfo

// GenesisState defines the poolrebalancer module's genesis state.
type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// pending_redelegations allow restoring in-flight state on restart.
	// They are optional for initial deployments.
	PendingRedelegations []PendingRedelegation `protobuf:"bytes,2,rep,name=pending_redelegations,json=pendingRedelegations,proto3" json:"pending_redelegations"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcdfba81f65d424, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.poolrebalancer.v1.Params")
	proto.RegisterType((*PendingRedelegation)(nil), "cosmos.poolrebalancer.v1.PendingRedelegation")
	proto.RegisterType((*QueuedRedelegation)(nil), "cosmos.poolrebalancer.v1.QueuedRedelegation")
	proto.RegisterType((*GenesisState)(nil), "cosmos.poolrebalancer.v1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmos/poolrebalancer/v1/poolrebalancer.proto", fileDescriptor_3fcdfba81f65d424)
}

var fileDescriptor_3fcdfba81f65d424 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xe3, 0x24, 0x5f, 0xda, 0x6f, 0x52, 0xfa, 0xc7, 0x4d, 0x21, 0x54, 0xc2, 0xa9, 0xb2,
	0x2a, 0x82, 0xda, 0x4a, 0x40, 0x62, 0x87, 0x44, 0xa8, 0x84, 0xa8, 0x54, 0x35, 0x98, 0x8a, 0x05,
	0x1b, 0x6b, 0x6c, 0xdf, 0x3a, 0x56, 0x3d, 0x9e, 0xd1, 0xcc, 0xd8, 0x0a, 0x6f, 0xd1, 0x67, 0x61,
	0xc5, 0x23, 0x74, 0xd9, 0x0d, 0x12, 0x62, 0x51, 0xa0, 0x7d, 0x11, 0x34, 0x63, 0xc7, 0x2d, 0x6d,
	0xca, 0x82, 0x9d, 0x33, 0xe7, 0x9e, 0x7b, 0x67, 0x7e, 0x73, 0x32, 0x68, 0x27, 0xa0, 0x82, 0x50,
	0xe1, 0x30, 0x4a, 0x13, 0x0e, 0x3e, 0x4e, 0x70, 0x1a, 0x00, 0x77, 0xf2, 0xc1, 0x8d, 0x15, 0x9b,
	0x71, 0x2a, 0xa9, 0xd9, 0x2d, 0xca, 0xed, 0x1b, 0x62, 0x3e, 0xd8, 0xb4, 0xca, 0x46, 0x3e, 0x16,
	0xe0, 0xe4, 0x03, 0x1f, 0x24, 0x1e, 0x38, 0x01, 0x8d, 0xd3, 0xc2, 0xb9, 0xd9, 0x89, 0x68, 0x44,
	0xf5, 0xa7, 0xa3, 0xbe, 0xca, 0xd5, 0x5e, 0x44, 0x69, 0x94, 0x80, 0xa3, 0x7f, 0xf9, 0xd9, 0x91,
	0x23, 0x63, 0x02, 0x42, 0x62, 0xc2, 0x8a, 0x82, 0xfe, 0x97, 0x3a, 0x6a, 0x8d, 0x31, 0xc7, 0x44,
	0x98, 0xcf, 0xd1, 0x7d, 0x35, 0xd6, 0x0b, 0x21, 0x81, 0x08, 0x4b, 0xca, 0x3d, 0x1c, 0x86, 0x1c,
	0x84, 0xe8, 0x1a, 0x5b, 0xc6, 0xf6, 0xff, 0x6e, 0x47, 0xa9, 0xbb, 0x33, 0xf1, 0x55, 0xa1, 0x99,
	0x43, 0xb4, 0x41, 0xf0, 0xd4, 0x93, 0x98, 0x47, 0x20, 0xbd, 0x1c, 0x27, 0x71, 0xa8, 0x64, 0xd1,
	0xad, 0x6f, 0x19, 0xdb, 0xf7, 0xdc, 0x75, 0x82, 0xa7, 0x87, 0x5a, 0xfb, 0x50, 0x49, 0x6a, 0x52,
	0x75, 0x38, 0x4f, 0x4e, 0x38, 0x88, 0x09, 0x4d, 0x42, 0xcf, 0x67, 0xdd, 0x86, 0x36, 0x75, 0x2a,
	0xf5, 0x70, 0x26, 0x8e, 0x98, 0xf9, 0x18, 0xad, 0xa9, 0x49, 0x94, 0x09, 0x8f, 0x01, 0xf7, 0xfc,
	0x84, 0x06, 0xc7, 0xdd, 0xa6, 0x36, 0x2c, 0x13, 0x3c, 0x3d, 0x60, 0x62, 0x0c, 0x7c, 0xa4, 0x56,
	0xcd, 0x5d, 0xb4, 0xa2, 0x4a, 0x09, 0xcd, 0x41, 0xd7, 0x52, 0xd6, 0xfd, 0x4f, 0x9d, 0x61, 0xf4,
	0xe8, 0xf4, 0xbc, 0x57, 0xfb, 0x7e, 0xde, 0xdb, 0x28, 0x68, 0x8a, 0xf0, 0xd8, 0x8e, 0xa9, 0x43,
	0xb0, 0x9c, 0xd8, 0x6f, 0x53, 0xe9, 0x2e, 0x11, 0x3c, 0xdd, 0xa7, 0x39, 0x8c, 0x81, 0x1f, 0xb0,
	0xbd, 0xe6, 0x62, 0x6b, 0x75, 0xc1, 0x7d, 0x90, 0x09, 0xf0, 0xb2, 0xb4, 0xa4, 0x02, 0xde, 0x11,
	0x4e, 0x12, 0x1f, 0x07, 0xc7, 0xfd, 0xcf, 0x75, 0xb4, 0x3e, 0x86, 0x34, 0x8c, 0xd3, 0xc8, 0x85,
	0x52, 0x8e, 0x69, 0x6a, 0x3e, 0x41, 0x6b, 0x77, 0x21, 0x5c, 0x0d, 0xe7, 0xe0, 0x13, 0x3c, 0xb8,
	0xe2, 0x56, 0x19, 0xea, 0xda, 0xb0, 0x2e, 0x78, 0x50, 0x81, 0xbb, 0xe6, 0x09, 0x85, 0x9c, 0xe3,
	0x69, 0x14, 0x9e, 0x50, 0xc8, 0x5b, 0x9e, 0x17, 0xa8, 0x85, 0x09, 0xcd, 0x52, 0xa9, 0x89, 0xb5,
	0x87, 0x0f, 0xed, 0x32, 0x69, 0x2a, 0x4f, 0x76, 0x99, 0x27, 0xfb, 0x35, 0x8d, 0xd3, 0x51, 0x53,
	0x31, 0x72, 0xcb, 0x72, 0x73, 0x1f, 0xad, 0x04, 0x94, 0xb0, 0x04, 0xd4, 0xd9, 0x3c, 0x15, 0x1f,
	0x8d, 0xb2, 0x3d, 0xdc, 0xb4, 0x8b, 0x6c, 0xd9, 0xb3, 0x6c, 0xd9, 0x87, 0xb3, 0x6c, 0x8d, 0x16,
	0x55, 0x8b, 0x93, 0x1f, 0x3d, 0xc3, 0x5d, 0xbe, 0x32, 0x2b, 0xb9, 0x1f, 0x20, 0xf3, 0x5d, 0x06,
	0x19, 0x84, 0x7f, 0x20, 0xdb, 0x47, 0x0b, 0x90, 0x4a, 0x1e, 0x83, 0x02, 0xd5, 0xd8, 0x6e, 0x0f,
	0x77, 0xec, 0xbb, 0xfe, 0x08, 0xf6, 0x1c, 0xe4, 0xe5, 0x96, 0x67, 0x3d, 0xfa, 0x5f, 0x0d, 0xb4,
	0xf4, 0x06, 0x52, 0x10, 0xb1, 0x78, 0x2f, 0xb1, 0x04, 0xf3, 0x25, 0x6a, 0x31, 0x1d, 0x72, 0x7d,
	0x0f, 0xed, 0xe1, 0xd6, 0x5f, 0xda, 0xeb, 0xba, 0x19, 0x84, 0xc2, 0x65, 0x4e, 0xd0, 0x06, 0x2b,
	0xc6, 0x7a, 0xfc, 0xda, 0x5c, 0x75, 0x4b, 0xff, 0xbc, 0xdb, 0x0e, 0xbb, 0x2d, 0x89, 0xbd, 0xe6,
	0x62, 0x63, 0xb5, 0xe9, 0x56, 0xd3, 0xaa, 0xdc, 0x29, 0x71, 0xb4, 0x77, 0xfa, 0xcb, 0xaa, 0x9d,
	0x5e, 0x58, 0xc6, 0xd9, 0x85, 0x65, 0xfc, 0xbc, 0xb0, 0x8c, 0x93, 0x4b, 0xab, 0x76, 0x76, 0x69,
	0xd5, 0xbe, 0x5d, 0x5a, 0xb5, 0x8f, 0x4f, 0xa3, 0x58, 0x4e, 0x32, 0xdf, 0x0e, 0x28, 0x71, 0xca,
	0xc7, 0x02, 0x72, 0xe2, 0x4c, 0x6f, 0xbe, 0x3d, 0xf2, 0x13, 0x03, 0xe1, 0xb7, 0xf4, 0xb5, 0x3d,
	0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xbd, 0xa4, 0xa3, 0xa1, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxMovePerOp.Size()
		i -= size
		if _, err := m.MaxMovePerOp.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MaxOpsPerBlock != 0 {
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(m.MaxOpsPerBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.RebalanceThresholdBp != 0 {
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(m.RebalanceThresholdBp))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxTargetValidators != 0 {
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(m.MaxTargetValidators))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolDelegatorAddress) > 0 {
		i -= len(m.PoolDelegatorAddress)
		copy(dAtA[i:], m.PoolDelegatorAddress)
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(len(m.PoolDelegatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingRedelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingRedelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingRedelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPoolrebalancer(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.DstValidatorAddress) > 0 {
		i -= len(m.DstValidatorAddress)
		copy(dAtA[i:], m.DstValidatorAddress)
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(len(m.DstValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SrcValidatorAddress) > 0 {
		i -= len(m.SrcValidatorAddress)
		copy(dAtA[i:], m.SrcValidatorAddress)
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(len(m.SrcValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueuedRedelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedRedelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedRedelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoolrebalancer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingRedelegations) > 0 {
		for iNdEx := len(m.PendingRedelegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingRedelegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoolrebalancer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolrebalancer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintPoolrebalancer(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolrebalancer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolDelegatorAddress)
	if l > 0 {
		n += 1 + l + sovPoolrebalancer(uint64(l))
	}
	if m.MaxTargetValidators != 0 {
		n += 1 + sovPoolrebalancer(uint64(m.MaxTargetValidators))
	}
	if m.RebalanceThresholdBp != 0 {
		n += 1 + sovPoolrebalancer(uint64(m.RebalanceThresholdBp))
	}
	if m.MaxOpsPerBlock != 0 {
		n += 1 + sovPoolrebalancer(uint64(m.MaxOpsPerBlock))
	}
	l = m.MaxMovePerOp.Size()
	n += 1 + l + sovPoolrebalancer(uint64(l))
	return n
}

func (m *PendingRedelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovPoolrebalancer(uint64(l))
	}
	l = len(m.SrcValidatorAddress)
	if l > 0 {
		n += 1 + l + sovPoolrebalancer(uint64(l))
	}
	l = len(m.DstValidatorAddress)
	if l > 0 {
		n += 1 + l + sovPoolrebalancer(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovPoolrebalancer(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovPoolrebalancer(uint64(l))
	return n
}

func (m *QueuedRedelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovPoolrebalancer(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovPoolrebalancer(uint64(l))
	if len(m.PendingRedelegations) > 0 {
		for _, e := range m.PendingRedelegations {
			l = e.Size()
			n += 1 + l + sovPoolrebalancer(uint64(l))
		}
	}
	return n
}

func sovPoolrebalancer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolrebalancer(x uint64) (n int) {
	return sovPoolrebalancer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolrebalancer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolDelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolDelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTargetValidators", wireType)
			}
			m.MaxTargetValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTargetValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RebalanceThresholdBp", wireType)
			}
			m.RebalanceThresholdBp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RebalanceThresholdBp |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOpsPerBlock", wireType)
			}
			m.MaxOpsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOpsPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMovePerOp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxMovePerOp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolrebalancer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingRedelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolrebalancer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingRedelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingRedelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DstValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolrebalancer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedRedelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolrebalancer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedRedelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedRedelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, PendingRedelegation{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolrebalancer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolrebalancer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingRedelegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingRedelegations = append(m.PendingRedelegations, PendingRedelegation{})
			if err := m.PendingRedelegations[len(m.PendingRedelegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolrebalancer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolrebalancer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolrebalancer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolrebalancer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolrebalancer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolrebalancer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolrebalancer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolrebalancer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolrebalancer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolrebalancer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolrebalancer = fmt.Errorf("proto: unexpected end of group")
)
