// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/bridge/v1/bridge.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the x/bridge module parameters.
type Params struct {
	// authorized_contract is the hex EVM address of the authorized bridge contract.
	AuthorizedContract string `protobuf:"bytes,1,opt,name=authorized_contract,json=authorizedContract,proto3" json:"authorized_contract"`
	// hyperlane_mailbox is the hex EVM address of the Hyperlane Mailbox.
	HyperlaneMailbox string `protobuf:"bytes,2,opt,name=hyperlane_mailbox,json=hyperlaneMailbox,proto3" json:"hyperlane_mailbox"`
	// base_domain_id is the Hyperlane domain ID for Base (default 8453).
	BaseDomainId uint32 `protobuf:"varint,3,opt,name=base_domain_id,json=baseDomainId,proto3" json:"base_domain_id"`
	// enabled indicates whether the bridge is active.
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled"`
	// max_transfer_amount is the maximum amount per transfer.
	MaxTransferAmount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=max_transfer_amount,json=maxTransferAmount,proto3,customtype=cosmossdk.io/math.Int" json:"max_transfer_amount"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_487e8d07176c0b42, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthorizedContract() string {
	if m != nil {
		return m.AuthorizedContract
	}
	return ""
}

func (m *Params) GetHyperlaneMailbox() string {
	if m != nil {
		return m.HyperlaneMailbox
	}
	return ""
}

func (m *Params) GetBaseDomainId() uint32 {
	if m != nil {
		return m.BaseDomainId
	}
	return 0
}

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.bridge.v1.Params")
}

func init() { proto.RegisterFile("cosmos/bridge/v1/bridge.proto", fileDescriptor_487e8d07176c0b42) }

var fileDescriptor_487e8d07176c0b42 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xe3, 0x40,
	0x1c, 0xc7, 0x33, 0xdb, 0xdd, 0xee, 0x6e, 0xd8, 0x5d, 0xda, 0x74, 0xff, 0x84, 0xae, 0x26, 0x45,
	0x3c, 0x94, 0x1e, 0x12, 0x8a, 0x27, 0x05, 0x05, 0xa3, 0x20, 0x3d, 0x14, 0x44, 0x3c, 0x79, 0x09,
	0x93, 0x64, 0x4c, 0x06, 0x3b, 0x33, 0x65, 0x32, 0x2d, 0xa9, 0x8f, 0xe0, 0x49, 0xf0, 0x25, 0x3c,
	0xf6, 0x31, 0x7a, 0xec, 0x51, 0x3c, 0x04, 0x69, 0x0f, 0x85, 0x3c, 0x85, 0x34, 0x93, 0x5a, 0xd0,
	0x5e, 0xc2, 0x2f, 0x9f, 0x4f, 0x7e, 0xdf, 0x0c, 0xf3, 0x55, 0xb7, 0x7d, 0x16, 0x13, 0x16, 0xdb,
	0x1e, 0xc7, 0x41, 0x88, 0xec, 0x61, 0xbb, 0x98, 0xac, 0x3e, 0x67, 0x82, 0x69, 0x15, 0xa9, 0xad,
	0x02, 0x0e, 0xdb, 0xf5, 0x2a, 0x24, 0x98, 0x32, 0x3b, 0x7f, 0xca, 0x8f, 0xea, 0xbf, 0x43, 0x16,
	0xb2, 0x7c, 0xb4, 0x97, 0x93, 0xa4, 0x3b, 0x0f, 0x25, 0xb5, 0x7c, 0x0e, 0x39, 0x24, 0xb1, 0xd6,
	0x55, 0x6b, 0x70, 0x20, 0x22, 0xc6, 0xf1, 0x2d, 0x0a, 0x5c, 0x9f, 0x51, 0xc1, 0xa1, 0x2f, 0x74,
	0xd0, 0x00, 0xcd, 0xef, 0xce, 0x56, 0x96, 0x9a, 0x9b, 0xf4, 0xe3, 0x62, 0xdc, 0x02, 0x17, 0xda,
	0xda, 0x9c, 0x14, 0x42, 0x3b, 0x53, 0xab, 0xd1, 0xa8, 0x8f, 0x78, 0x0f, 0x52, 0xe4, 0x12, 0x88,
	0x7b, 0x1e, 0x4b, 0xf4, 0x4f, 0x79, 0x58, 0x3d, 0x4b, 0xcd, 0x8f, 0x52, 0x46, 0x55, 0xde, 0x78,
	0x57, 0x62, 0xed, 0x50, 0xfd, 0xe5, 0xc1, 0x18, 0xb9, 0x01, 0x23, 0x10, 0x53, 0x17, 0x07, 0x7a,
	0xa9, 0x01, 0x9a, 0x3f, 0x9d, 0x7f, 0x59, 0x6a, 0xbe, 0x33, 0x32, 0xe2, 0xc7, 0x12, 0x9e, 0xe6,
	0xac, 0x13, 0x68, 0x2d, 0xf5, 0x2b, 0xa2, 0xd0, 0xeb, 0xa1, 0x40, 0xff, 0xdc, 0x00, 0xcd, 0x6f,
	0x4e, 0x25, 0x4b, 0xcd, 0x15, 0x92, 0x0b, 0xab, 0x37, 0x0d, 0xab, 0x35, 0x02, 0x13, 0x57, 0x70,
	0x48, 0xe3, 0x6b, 0xc4, 0x5d, 0x48, 0xd8, 0x80, 0x0a, 0xfd, 0x4b, 0x7e, 0xea, 0xfd, 0x49, 0x6a,
	0x2a, 0xcf, 0xa9, 0xf9, 0x47, 0xde, 0x76, 0x1c, 0xdc, 0x58, 0x98, 0xd9, 0x04, 0x8a, 0xc8, 0xea,
	0x50, 0xb1, 0xbc, 0x9f, 0x0d, 0xbb, 0xf2, 0x07, 0x55, 0x02, 0x93, 0xcb, 0x42, 0x1c, 0xe7, 0xfc,
	0xe0, 0xff, 0xdd, 0x62, 0xdc, 0xfa, 0x5b, 0xf4, 0x9a, 0xac, 0x9a, 0x95, 0x55, 0x38, 0x47, 0x93,
	0x99, 0x01, 0xa6, 0x33, 0x03, 0xbc, 0xcc, 0x0c, 0x70, 0x3f, 0x37, 0x94, 0xe9, 0xdc, 0x50, 0x9e,
	0xe6, 0x86, 0x72, 0xb5, 0x1b, 0x62, 0x11, 0x0d, 0x3c, 0xcb, 0x67, 0xc4, 0x2e, 0x96, 0xd1, 0x90,
	0xac, 0x03, 0xc4, 0xa8, 0x8f, 0x62, 0xaf, 0x9c, 0x97, 0xbb, 0xf7, 0x1a, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0xee, 0xf9, 0x6f, 0x38, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxTransferAmount.Size()
		i -= size
		if _, err := m.MaxTransferAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBridge(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.BaseDomainId != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.BaseDomainId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.HyperlaneMailbox) > 0 {
		i -= len(m.HyperlaneMailbox)
		copy(dAtA[i:], m.HyperlaneMailbox)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.HyperlaneMailbox)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorizedContract) > 0 {
		i -= len(m.AuthorizedContract)
		copy(dAtA[i:], m.AuthorizedContract)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.AuthorizedContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridge(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorizedContract)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.HyperlaneMailbox)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	if m.BaseDomainId != 0 {
		n += 1 + sovBridge(uint64(m.BaseDomainId))
	}
	if m.Enabled {
		n += 2
	}
	l = m.MaxTransferAmount.Size()
	n += 1 + l + sovBridge(uint64(l))
	return n
}

func sovBridge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridge(x uint64) (n int) {
	return sovBridge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HyperlaneMailbox", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HyperlaneMailbox = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDomainId", wireType)
			}
			m.BaseDomainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseDomainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTransferAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxTransferAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridge = fmt.Errorf("proto: unexpected end of group")
)
