// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/svip/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the svip module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the svip module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// total_distributed is the cumulative tokens sent to FeeCollector.
	TotalDistributed cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_distributed,json=totalDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"total_distributed"`
	// activation_time is when SVIP was activated. Zero if not yet activated.
	ActivationTime time.Time `protobuf:"bytes,3,opt,name=activation_time,json=activationTime,proto3,stdtime" json:"activation_time"`
	// pool_balance_at_activation is the pool snapshot used to derive R₀.
	PoolBalanceAtActivation cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=pool_balance_at_activation,json=poolBalanceAtActivation,proto3,customtype=cosmossdk.io/math.Int" json:"pool_balance_at_activation"`
	// last_block_time is the timestamp of the last processed block.
	LastBlockTime time.Time `protobuf:"bytes,5,opt,name=last_block_time,json=lastBlockTime,proto3,stdtime" json:"last_block_time"`
	// total_paused_seconds is the cumulative seconds spent in paused state.
	TotalPausedSeconds int64 `protobuf:"varint,6,opt,name=total_paused_seconds,json=totalPausedSeconds,proto3" json:"total_paused_seconds,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fc4f2cc3c482b1c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetActivationTime() time.Time {
	if m != nil {
		return m.ActivationTime
	}
	return time.Time{}
}

func (m *GenesisState) GetLastBlockTime() time.Time {
	if m != nil {
		return m.LastBlockTime
	}
	return time.Time{}
}

func (m *GenesisState) GetTotalPausedSeconds() int64 {
	if m != nil {
		return m.TotalPausedSeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.svip.v1.GenesisState")
}

func init() { proto.RegisterFile("cosmos/svip/v1/genesis.proto", fileDescriptor_9fc4f2cc3c482b1c) }

var fileDescriptor_9fc4f2cc3c482b1c = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x6f, 0xd4, 0x30,
	0x14, 0xc7, 0xcf, 0x1c, 0x9c, 0xa8, 0x81, 0x96, 0x46, 0x05, 0xc2, 0x09, 0x92, 0x53, 0xa7, 0x13,
	0x83, 0x4d, 0x61, 0x42, 0x62, 0x69, 0x84, 0x84, 0x40, 0x20, 0x55, 0x29, 0x53, 0x97, 0xc8, 0x49,
	0x4c, 0x6a, 0x35, 0xce, 0x8b, 0xce, 0x2f, 0x11, 0x7c, 0x8b, 0x7e, 0x0c, 0x46, 0x3e, 0x02, 0x63,
	0xc7, 0x8e, 0x88, 0xa1, 0xa0, 0xbb, 0x81, 0xaf, 0x81, 0x6c, 0xa7, 0x9c, 0x60, 0x82, 0x25, 0x72,
	0xf2, 0x7f, 0xbf, 0x97, 0xdf, 0xb3, 0x1e, 0x7d, 0x50, 0x80, 0xd1, 0x60, 0xb8, 0xe9, 0x55, 0xcb,
	0xfb, 0x3d, 0x5e, 0xc9, 0x46, 0x1a, 0x65, 0x58, 0xbb, 0x00, 0x84, 0x60, 0xd3, 0xa7, 0xcc, 0xa6,
	0xac, 0xdf, 0x9b, 0x6e, 0x0b, 0xad, 0x1a, 0xe0, 0xee, 0xe9, 0x4b, 0xa6, 0xf7, 0xff, 0x6a, 0xe0,
	0x4a, 0x7d, 0xb4, 0x53, 0x41, 0x05, 0xee, 0xc8, 0xed, 0x69, 0xf8, 0x1a, 0x57, 0x00, 0x55, 0x2d,
	0xb9, 0x7b, 0xcb, 0xbb, 0xf7, 0x1c, 0x95, 0x96, 0x06, 0x85, 0x1e, 0xb0, 0xdd, 0x2f, 0x63, 0x7a,
	0xf3, 0xa5, 0xd7, 0x38, 0x44, 0x81, 0x32, 0x78, 0x46, 0x27, 0xad, 0x58, 0x08, 0x6d, 0x42, 0x32,
	0x23, 0xf3, 0x1b, 0x4f, 0xee, 0xb2, 0x3f, 0xb5, 0xd8, 0x81, 0x4b, 0x93, 0x8d, 0xb3, 0x8b, 0x78,
	0xf4, 0xe9, 0xe7, 0xe7, 0x47, 0x24, 0x1d, 0x80, 0xe0, 0x35, 0xdd, 0x46, 0x40, 0x51, 0x67, 0xa5,
	0x32, 0xb8, 0x50, 0x79, 0x87, 0xb2, 0x0c, 0xaf, 0xcc, 0xc8, 0x7c, 0x23, 0x79, 0x68, 0xab, 0xbf,
	0x5d, 0xc4, 0x77, 0x7c, 0x33, 0x53, 0x9e, 0x30, 0x05, 0x5c, 0x0b, 0x3c, 0x66, 0xaf, 0x1a, 0x4c,
	0x6f, 0x3b, 0xee, 0xc5, 0x1a, 0x0b, 0xde, 0xd2, 0x2d, 0x51, 0xa0, 0xea, 0x05, 0x2a, 0x68, 0x32,
	0x6b, 0x1d, 0x8e, 0x9d, 0xcf, 0x94, 0xf9, 0x91, 0xd8, 0xe5, 0x48, 0xec, 0xdd, 0xe5, 0x48, 0xc9,
	0x75, 0xfb, 0x97, 0xd3, 0xef, 0x31, 0x49, 0x37, 0xd7, 0xb0, 0x8d, 0x83, 0x23, 0x3a, 0x6d, 0x01,
	0xea, 0x2c, 0x17, 0xb5, 0x68, 0x0a, 0x99, 0x09, 0xcc, 0xd6, 0x15, 0xe1, 0xd5, 0x7f, 0x71, 0xbc,
	0x67, 0x1b, 0x24, 0x9e, 0xdf, 0xc7, 0xfd, 0xdf, 0x74, 0xf0, 0x86, 0x6e, 0xd5, 0xc2, 0x60, 0x96,
	0xd7, 0x50, 0x9c, 0x78, 0xd5, 0x6b, 0xff, 0xa1, 0x7a, 0xcb, 0xc2, 0x89, 0x65, 0x9d, 0xe9, 0x63,
	0xba, 0xe3, 0x2f, 0xb1, 0x15, 0x9d, 0x91, 0x65, 0x66, 0x64, 0x01, 0x4d, 0x69, 0xc2, 0xc9, 0x8c,
	0xcc, 0xc7, 0x69, 0xe0, 0xb2, 0x03, 0x17, 0x1d, 0xfa, 0x24, 0x79, 0x7e, 0xb6, 0x8c, 0xc8, 0xf9,
	0x32, 0x22, 0x3f, 0x96, 0x11, 0x39, 0x5d, 0x45, 0xa3, 0xf3, 0x55, 0x34, 0xfa, 0xba, 0x8a, 0x46,
	0x47, 0xbb, 0x95, 0xc2, 0xe3, 0x2e, 0x67, 0x05, 0x68, 0x3e, 0x6c, 0x8e, 0xec, 0x35, 0xff, 0xe0,
	0xf7, 0x07, 0x3f, 0xb6, 0xd2, 0xe4, 0x13, 0x27, 0xf7, 0xf4, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x8a, 0x9c, 0x81, 0x9c, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalPausedSeconds != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TotalPausedSeconds))
		i--
		dAtA[i] = 0x30
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastBlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastBlockTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintGenesis(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	{
		size := m.PoolBalanceAtActivation.Size()
		i -= size
		if _, err := m.PoolBalanceAtActivation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ActivationTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActivationTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintGenesis(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalDistributed.Size()
		i -= size
		if _, err := m.TotalDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalDistributed.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActivationTime)
	n += 1 + l + sovGenesis(uint64(l))
	l = m.PoolBalanceAtActivation.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastBlockTime)
	n += 1 + l + sovGenesis(uint64(l))
	if m.TotalPausedSeconds != 0 {
		n += 1 + sovGenesis(uint64(m.TotalPausedSeconds))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ActivationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolBalanceAtActivation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolBalanceAtActivation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastBlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPausedSeconds", wireType)
			}
			m.TotalPausedSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPausedSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
