// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/svip/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest defines the request type for querying x/svip parameters.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdeace1067afd47, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse defines the response type for querying x/svip parameters.
type QueryParamsResponse struct {
	// params define the svip module parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdeace1067afd47, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryPoolStateRequest defines the request type for querying pool state.
type QueryPoolStateRequest struct {
}

func (m *QueryPoolStateRequest) Reset()         { *m = QueryPoolStateRequest{} }
func (m *QueryPoolStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPoolStateRequest) ProtoMessage()    {}
func (*QueryPoolStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdeace1067afd47, []int{2}
}
func (m *QueryPoolStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPoolStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPoolStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPoolStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolStateRequest.Merge(m, src)
}
func (m *QueryPoolStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPoolStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolStateRequest proto.InternalMessageInfo

// QueryPoolStateResponse returns the current SVIP pool state.
type QueryPoolStateResponse struct {
	// pool_balance is the current balance in the SVIP module account.
	PoolBalance types.Coin `protobuf:"bytes,1,opt,name=pool_balance,json=poolBalance,proto3" json:"pool_balance"`
	// total_distributed is cumulative tokens sent to FeeCollector.
	TotalDistributed cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_distributed,json=totalDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"total_distributed"`
	// current_rate_per_second is the current reward rate after decay.
	CurrentRatePerSecond cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=current_rate_per_second,json=currentRatePerSecond,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"current_rate_per_second"`
	// activated indicates whether SVIP is active.
	Activated bool `protobuf:"varint,4,opt,name=activated,proto3" json:"activated,omitempty"`
	// paused indicates whether SVIP is paused.
	Paused bool `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty"`
	// activation_time is when SVIP was activated.
	ActivationTime time.Time `protobuf:"bytes,6,opt,name=activation_time,json=activationTime,proto3,stdtime" json:"activation_time"`
}

func (m *QueryPoolStateResponse) Reset()         { *m = QueryPoolStateResponse{} }
func (m *QueryPoolStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPoolStateResponse) ProtoMessage()    {}
func (*QueryPoolStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdeace1067afd47, []int{3}
}
func (m *QueryPoolStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPoolStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPoolStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPoolStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolStateResponse.Merge(m, src)
}
func (m *QueryPoolStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPoolStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolStateResponse proto.InternalMessageInfo

func (m *QueryPoolStateResponse) GetPoolBalance() types.Coin {
	if m != nil {
		return m.PoolBalance
	}
	return types.Coin{}
}

func (m *QueryPoolStateResponse) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *QueryPoolStateResponse) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *QueryPoolStateResponse) GetActivationTime() time.Time {
	if m != nil {
		return m.ActivationTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.svip.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.svip.v1.QueryParamsResponse")
	proto.RegisterType((*QueryPoolStateRequest)(nil), "cosmos.svip.v1.QueryPoolStateRequest")
	proto.RegisterType((*QueryPoolStateResponse)(nil), "cosmos.svip.v1.QueryPoolStateResponse")
}

func init() { proto.RegisterFile("cosmos/svip/v1/query.proto", fileDescriptor_fcdeace1067afd47) }

var fileDescriptor_fcdeace1067afd47 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x3d, 0x6f, 0xd3, 0x4c,
	0x1c, 0x8f, 0xfb, 0x12, 0x35, 0xd7, 0x47, 0x7d, 0xe8, 0xd1, 0xa6, 0xa9, 0x29, 0x4e, 0xe5, 0x0a,
	0x54, 0x31, 0xdc, 0x29, 0x65, 0x42, 0x62, 0x32, 0x5d, 0x40, 0x20, 0x15, 0x97, 0xa9, 0x4b, 0x74,
	0x76, 0x0e, 0xf7, 0x44, 0x7c, 0xe7, 0xfa, 0xce, 0x16, 0x5d, 0x18, 0xd8, 0xd8, 0x2a, 0xf1, 0x25,
	0x18, 0xf9, 0x18, 0x1d, 0x2b, 0xb1, 0x20, 0x86, 0x82, 0x5a, 0x24, 0xbe, 0x03, 0x13, 0xba, 0x17,
	0x53, 0x35, 0x41, 0xb0, 0x44, 0xf6, 0xfd, 0xde, 0xfc, 0xbf, 0xff, 0x2f, 0xc0, 0x4f, 0x85, 0xcc,
	0x85, 0xc4, 0xb2, 0x66, 0x05, 0xae, 0x07, 0xf8, 0xa8, 0xa2, 0xe5, 0x31, 0x2a, 0x4a, 0xa1, 0x04,
	0x5c, 0xb2, 0x18, 0xd2, 0x18, 0xaa, 0x07, 0xfe, 0x32, 0xc9, 0x19, 0x17, 0xd8, 0xfc, 0x5a, 0x8a,
	0xbf, 0x3e, 0x21, 0x37, 0x54, 0x0b, 0xad, 0x64, 0x22, 0x13, 0xe6, 0x11, 0xeb, 0x27, 0x77, 0xba,
	0x91, 0x09, 0x91, 0x8d, 0x29, 0x26, 0x05, 0xc3, 0x84, 0x73, 0xa1, 0x88, 0x62, 0x82, 0x4b, 0x87,
	0xf6, 0x1d, 0x6a, 0xde, 0x92, 0xea, 0x25, 0x56, 0x2c, 0xa7, 0x52, 0x91, 0xbc, 0x31, 0x0d, 0x5c,
	0x5e, 0x42, 0x24, 0xc5, 0xf5, 0x20, 0xa1, 0x8a, 0x0c, 0x70, 0x2a, 0x18, 0xb7, 0x78, 0xb8, 0x02,
	0xe0, 0x73, 0x3d, 0xc1, 0x1e, 0x29, 0x49, 0x2e, 0x63, 0x7a, 0x54, 0x51, 0xa9, 0xc2, 0x3d, 0x70,
	0xf3, 0xda, 0xa9, 0x2c, 0x04, 0x97, 0x14, 0x3e, 0x00, 0xed, 0xc2, 0x9c, 0xf4, 0xbc, 0x4d, 0x6f,
	0x7b, 0x71, 0xa7, 0x8b, 0xae, 0x0f, 0x8c, 0x2c, 0x3f, 0xea, 0x9c, 0x9e, 0xf7, 0x5b, 0x1f, 0x7e,
	0x7c, 0xbc, 0xe7, 0xc5, 0x4e, 0x10, 0xae, 0x81, 0x55, 0xeb, 0x28, 0xc4, 0x78, 0x5f, 0x11, 0x45,
	0x9b, 0xa8, 0x77, 0xb3, 0xa0, 0x3b, 0x89, 0xb8, 0xb8, 0x08, 0xfc, 0x57, 0x08, 0x31, 0x1e, 0x26,
	0x64, 0x4c, 0x78, 0x4a, 0x5d, 0xe8, 0x7a, 0x13, 0xaa, 0x47, 0x42, 0x6e, 0x24, 0xf4, 0x48, 0x30,
	0x1e, 0xcd, 0xe9, 0xdc, 0x78, 0x51, 0x8b, 0x22, 0xab, 0x81, 0x4f, 0xc0, 0xb2, 0x12, 0x8a, 0x8c,
	0x87, 0x23, 0x26, 0x55, 0xc9, 0x92, 0x4a, 0xd1, 0x51, 0x6f, 0x66, 0xd3, 0xdb, 0xee, 0x44, 0xb7,
	0x35, 0xfb, 0xcb, 0x79, 0x7f, 0xd5, 0xfa, 0xc9, 0xd1, 0x2b, 0xc4, 0x04, 0xce, 0x89, 0x3a, 0x44,
	0x8f, 0xb9, 0x8a, 0x6f, 0x18, 0xdd, 0xee, 0x95, 0x0c, 0x1e, 0x80, 0xb5, 0xb4, 0x2a, 0x4b, 0xca,
	0xd5, 0xb0, 0x24, 0x8a, 0x0e, 0x0b, 0x5a, 0x0e, 0x25, 0x4d, 0x05, 0x1f, 0xf5, 0x66, 0x8d, 0xe3,
	0x96, 0x73, 0xbc, 0x35, 0xed, 0xf8, 0x94, 0x66, 0x24, 0x3d, 0xde, 0xa5, 0x69, 0xbc, 0xe2, 0x3c,
	0x62, 0xa2, 0xe8, 0x1e, 0x2d, 0xf7, 0x8d, 0x01, 0xdc, 0x00, 0x1d, 0x92, 0x2a, 0x56, 0x13, 0xfd,
	0x7d, 0x73, 0x9b, 0xde, 0xf6, 0x42, 0x7c, 0x75, 0x00, 0xbb, 0xfa, 0xe2, 0x2b, 0x49, 0x47, 0xbd,
	0x79, 0x03, 0xb9, 0x37, 0xf8, 0x0c, 0xfc, 0xef, 0x48, 0x4c, 0xf0, 0xa1, 0xde, 0x7d, 0xaf, 0x6d,
	0x2e, 0xc9, 0x47, 0xb6, 0x18, 0xa8, 0x29, 0x06, 0x7a, 0xd1, 0x14, 0x23, 0x5a, 0xd0, 0x5f, 0x79,
	0xf2, 0xb5, 0xef, 0xc5, 0x4b, 0x57, 0x62, 0x0d, 0xef, 0xfc, 0xf4, 0xc0, 0xbc, 0xd9, 0x05, 0x3c,
	0x02, 0x6d, 0xbb, 0x4b, 0x18, 0x4e, 0xee, 0x78, 0xba, 0x2e, 0xfe, 0xd6, 0x5f, 0x39, 0x76, 0x9b,
	0x61, 0xf0, 0xf6, 0xd3, 0xf7, 0xf7, 0x33, 0x3d, 0xd8, 0xc5, 0x13, 0x7f, 0x01, 0xdb, 0x10, 0xf8,
	0x06, 0x74, 0x7e, 0x57, 0x00, 0xde, 0xf9, 0xb3, 0xe3, 0x44, 0x79, 0xfc, 0xbb, 0xff, 0xa2, 0xb9,
	0xec, 0xd0, 0x64, 0x6f, 0x40, 0x7f, 0x2a, 0x5b, 0xf7, 0x4b, 0x6a, 0x6e, 0xf4, 0xf0, 0xf4, 0x22,
	0xf0, 0xce, 0x2e, 0x02, 0xef, 0xdb, 0x45, 0xe0, 0x9d, 0x5c, 0x06, 0xad, 0xb3, 0xcb, 0xa0, 0xf5,
	0xf9, 0x32, 0x68, 0x1d, 0x84, 0x19, 0x53, 0x87, 0x55, 0x82, 0x52, 0x91, 0x37, 0x7a, 0x5a, 0xe7,
	0xf8, 0xb5, 0x75, 0x51, 0xc7, 0x05, 0x95, 0x49, 0xdb, 0x5c, 0xf4, 0xfd, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa5, 0x62, 0xe6, 0x7b, 0x1f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of x/svip module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// PoolState queries the current SVIP pool balance, distribution stats, and
	// reward rate.
	PoolState(ctx context.Context, in *QueryPoolStateRequest, opts ...grpc.CallOption) (*QueryPoolStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.svip.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PoolState(ctx context.Context, in *QueryPoolStateRequest, opts ...grpc.CallOption) (*QueryPoolStateResponse, error) {
	out := new(QueryPoolStateResponse)
	err := c.cc.Invoke(ctx, "/cosmos.svip.v1.Query/PoolState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of x/svip module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// PoolState queries the current SVIP pool balance, distribution stats, and
	// reward rate.
	PoolState(context.Context, *QueryPoolStateRequest) (*QueryPoolStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PoolState(ctx context.Context, req *QueryPoolStateRequest) (*QueryPoolStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolState not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.svip.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PoolState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPoolStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PoolState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.svip.v1.Query/PoolState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PoolState(ctx, req.(*QueryPoolStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.svip.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PoolState",
			Handler:    _Query_PoolState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/svip/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPoolStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPoolStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPoolStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPoolStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPoolStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPoolStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ActivationTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActivationTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintQuery(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x32
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Activated {
		i--
		if m.Activated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.CurrentRatePerSecond.Size()
		i -= size
		if _, err := m.CurrentRatePerSecond.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalDistributed.Size()
		i -= size
		if _, err := m.TotalDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.PoolBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPoolStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPoolStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PoolBalance.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.TotalDistributed.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.CurrentRatePerSecond.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.Activated {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActivationTime)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPoolStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPoolStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPoolStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPoolStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPoolStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPoolStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentRatePerSecond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentRatePerSecond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Activated = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ActivationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
