// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/poolrebalancer/v1/query.proto

package poolrebalancerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName               = "/cosmos.poolrebalancer.v1.Query/Params"
	Query_PendingRedelegations_FullMethodName = "/cosmos.poolrebalancer.v1.Query/PendingRedelegations"
	Query_PendingUndelegations_FullMethodName = "/cosmos.poolrebalancer.v1.Query/PendingUndelegations"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the poolrebalancer module params.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// PendingRedelegations returns tracked in-flight redelegations.
	PendingRedelegations(ctx context.Context, in *QueryPendingRedelegationsRequest, opts ...grpc.CallOption) (*QueryPendingRedelegationsResponse, error)
	// PendingUndelegations returns tracked in-flight undelegations.
	PendingUndelegations(ctx context.Context, in *QueryPendingUndelegationsRequest, opts ...grpc.CallOption) (*QueryPendingUndelegationsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingRedelegations(ctx context.Context, in *QueryPendingRedelegationsRequest, opts ...grpc.CallOption) (*QueryPendingRedelegationsResponse, error) {
	out := new(QueryPendingRedelegationsResponse)
	err := c.cc.Invoke(ctx, Query_PendingRedelegations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingUndelegations(ctx context.Context, in *QueryPendingUndelegationsRequest, opts ...grpc.CallOption) (*QueryPendingUndelegationsResponse, error) {
	out := new(QueryPendingUndelegationsResponse)
	err := c.cc.Invoke(ctx, Query_PendingUndelegations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params returns the poolrebalancer module params.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// PendingRedelegations returns tracked in-flight redelegations.
	PendingRedelegations(context.Context, *QueryPendingRedelegationsRequest) (*QueryPendingRedelegationsResponse, error)
	// PendingUndelegations returns tracked in-flight undelegations.
	PendingUndelegations(context.Context, *QueryPendingUndelegationsRequest) (*QueryPendingUndelegationsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) PendingRedelegations(context.Context, *QueryPendingRedelegationsRequest) (*QueryPendingRedelegationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingRedelegations not implemented")
}
func (UnimplementedQueryServer) PendingUndelegations(context.Context, *QueryPendingUndelegationsRequest) (*QueryPendingUndelegationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingUndelegations not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingRedelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingRedelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingRedelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingRedelegations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingRedelegations(ctx, req.(*QueryPendingRedelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingUndelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingUndelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingUndelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingUndelegations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingUndelegations(ctx, req.(*QueryPendingUndelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.poolrebalancer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PendingRedelegations",
			Handler:    _Query_PendingRedelegations_Handler,
		},
		{
			MethodName: "PendingUndelegations",
			Handler:    _Query_PendingUndelegations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/poolrebalancer/v1/query.proto",
}
